version: '3'
services:
  db:
    image: "postgres:11.6-alpine"
    ports:
      - "5432:5432"
    env_file:
      - database.env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  cache:
    image: redis:6
    env_file:
      - .env
    ports:
      - "6379:6379"

  redisinsight:
    image: redislabs/redisinsight
    ports:
      - "8001:8001"